### GENERAL SETTINGS ###

# Site settings
title: GS Lab
description: "Open Source  @ GS Lab"
analytics: UA-50546869-2
baseurl: "/opensource" #important: start with /
url: "http://vinodborole.github.com/opensource"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FFC12D" #"#F70031" 
  primary_rgb: "255,193,45" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#2F4F4F" #"#33004D"
  link: "#428bca"
  link_hover: "#FFC12D"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url:
  - title: facebook
    url:
  - title: twitter
    url: 

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Amar Arma Genesis,
    - Baner Road, Baner, 
    - Pune 411045 India,
email: info@gslab.com
tel: +91 20 4671 1000


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Vinod Borole
    position: Associate Architect
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: Vinod_Borole_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vinod.borole@gslab.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Shital Patil
    position: Senior Software Engineer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: Shital_Patil_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:shital.patil@gslab.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Sumit Gandhi
    position: Software Engineer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: Sumit_Gandhi_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sumit.gandhi@gslab.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Abdul Waheed
    position: Software Engineer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: Abdul_Waheed_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:abdul.waheed@gslab.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: 
    img:

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We are committed to driving the growth of open source technologies, expanding the development of open standards and investing resources to provide for sustainable innovation."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: 
    author: 
    position:
